id: P0CE28C52
initial_creation_type: input
source_metadata:
  Title: Udayananirākaraṇam of Rantnakirti
  Editor: R.N.Pandey
  Publisher: Srisatguru Publications
  Place of Publication: Delhi
  Year: '1984'
  Prathamo'dhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyo'dhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīyo'dhyāyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:50:57.949570'
last_modified_at: '2022-03-08T16:50:57.949583'
